// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openFile: (path: string, encodingOverride: string | null) => typedError<FileContent, AppError>(__TAURI_INVOKE("open_file", { path, encodingOverride })),
	saveFile: (path: string, text: string, eol: Eol, hasBom: boolean, expectedHash: string | null) => typedError<SaveResult, AppError>(__TAURI_INVOKE("save_file", { path, text, eol, hasBom, expectedHash })),
	watchPaths: (paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("watch_paths", { paths })),
	showOpenDialog: () => typedError<string | null, AppError>(__TAURI_INVOKE("show_open_dialog")),
	showSaveDialog: (defaultName: string) => typedError<string | null, AppError>(__TAURI_INVOKE("show_save_dialog", { defaultName })),
};

/* Types */
/**  커맨드 실패의 종류. `{ kind, message }`로 직렬화되어 shared/ipc가 정규화한다. */
export type AppError = { kind: "notFound"; message: string } | { kind: "permission"; message: string } | { kind: "conflict"; message: string } | { kind: "diskFull"; message: string } | { kind: "encoding"; message: string } | { kind: "io"; message: string };

/**  판정된 EOL. IPC에서는 "lf"|"crlf" 문자열이다(→ rust-commands.md FileContent.eol). */
export type Eol = "lf" | "crlf";

/**
 *  open_file 반환값(→ rust-commands.md). text는 CM6용으로 LF 정규화되어 있고,
 *  저장 시 save_file이 `eol`로 되돌린다(→ file-lifecycle.md#eol-정책).
 */
export type FileContent = {
	text: string,
	encoding: string,
	hasBom: boolean,
	eol: Eol,
	eolMixed: boolean,
	/**  ms 단위라 2^53 안에 들므로 TS number로 내보낸다(specta는 u64를 기본 금지). */
	mtime: number,
	hash: string,
};

/**  save_file 반환값(→ rust-commands.md). hash는 방금 쓴 디스크 바이트의 내용 해시다. */
export type SaveResult = {
	/**  ms 단위라 2^53 안에 들므로 TS number로 내보낸다(specta는 u64를 기본 금지). */
	mtime: number,
	hash: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

